# Generated by Django 4.0.4 on 2022-06-10 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cliente_nombreusuario_alter_cliente_rut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.categoria'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombreusuario',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
