# Generated by Django 4.0.4 on 2022-06-14 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(choices=[[1, 'perro'], [3, 'roedor'], [5, 'gatos'], [6, 'aves'], [7, 'peces']], on_delete=django.db.models.deletion.PROTECT, to='app.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productoimg'),
        ),
    ]
