# Generated by Django 4.0.4 on 2022-06-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
