# Generated by Django 4.0.4 on 2022-06-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_pedido_nomusuario_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='nomproduc',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
